language: ruby
rvm:
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - ruby-head
  - jruby-head
  - ree

os:
  - linux
  - osx

addons:
  code_climate:
    repo_token: 55cf1cf5e30ba00fac00430a
